export const data=[{"id":1,"title":"Persistent","description":"Distributed multi-state workforce","image":"http://dummyimage.com/179x100.png/5fa2dd/ffffff","tags":"Baby"},
{"id":2,"title":"Front-line","description":"Team-oriented bandwidth-monitored secured line","image":"http://dummyimage.com/141x100.png/cc0000/ffffff","tags":"Clothing"},
{"id":3,"title":"Reverse-engineered","description":"Fully-configurable web-enabled complexity","image":"http://dummyimage.com/233x100.png/cc0000/ffffff","tags":"Computers"},
{"id":4,"title":"Upgradable","description":"Managed dedicated database","image":"http://dummyimage.com/236x100.png/5fa2dd/ffffff","tags":"Health"},
{"id":5,"title":"Sharable","description":"Phased empowering contingency","image":"http://dummyimage.com/250x100.png/cc0000/ffffff","tags":"Books"},
{"id":6,"title":"homogeneous","description":"Networked systemic model","image":"http://dummyimage.com/199x100.png/cc0000/ffffff","tags":"Sports"},
{"id":7,"title":"Multi-layered","description":"Enterprise-wide bottom-line initiative","image":"http://dummyimage.com/148x100.png/dddddd/000000","tags":"Kids"},
{"id":8,"title":"array","description":"Managed background process improvement","image":"http://dummyimage.com/244x100.png/5fa2dd/ffffff","tags":"Home"},
{"id":9,"title":"dynamic","description":"Upgradable content-based migration","image":"http://dummyimage.com/121x100.png/ff4444/ffffff","tags":"Grocery"},
{"id":10,"title":"attitude-oriented","description":"Object-based attitude-oriented orchestration","image":"http://dummyimage.com/242x100.png/5fa2dd/ffffff","tags":"Sports"},
{"id":11,"title":"policy","description":"Business-focused hybrid middleware","image":"http://dummyimage.com/137x100.png/dddddd/000000","tags":"Jewelry"},
{"id":12,"title":"Focused","description":"Integrated bottom-line moratorium","image":"http://dummyimage.com/209x100.png/5fa2dd/ffffff","tags":"Beauty"},
{"id":13,"title":"matrix","description":"Cross-group homogeneous installation","image":"http://dummyimage.com/226x100.png/5fa2dd/ffffff","tags":"Grocery"},
{"id":14,"title":"Synergized","description":"Synergized real-time archive","image":"http://dummyimage.com/166x100.png/cc0000/ffffff","tags":"Movies"},
{"id":15,"title":"Enhanced","description":"Inverse dedicated groupware","image":"http://dummyimage.com/189x100.png/dddddd/000000","tags":"Computers"},
{"id":16,"title":"architecture","description":"Configurable real-time encryption","image":"http://dummyimage.com/212x100.png/dddddd/000000","tags":"Kids"},
{"id":17,"title":"archive","description":"Programmable background hub","image":"http://dummyimage.com/191x100.png/cc0000/ffffff","tags":"Tools"},
{"id":18,"title":"didactic","description":"Public-key system-worthy open system","image":"http://dummyimage.com/170x100.png/ff4444/ffffff","tags":"Kids"},
{"id":19,"title":"value-added","description":"Implemented responsive interface","image":"http://dummyimage.com/207x100.png/5fa2dd/ffffff","tags":"Tools"},
{"id":20,"title":"multimedia","description":"Robust demand-driven standardization","image":"http://dummyimage.com/188x100.png/cc0000/ffffff","tags":"Clothing"},
{"id":21,"title":"firmware","description":"Monitored system-worthy info-mediaries","image":"http://dummyimage.com/228x100.png/cc0000/ffffff","tags":"Toys"},
{"id":22,"title":"migration","description":"Face to face attitude-oriented access","image":"http://dummyimage.com/240x100.png/dddddd/000000","tags":"Baby"},
{"id":23,"title":"Reverse-engineered","description":"Implemented real-time support","image":"http://dummyimage.com/228x100.png/cc0000/ffffff","tags":"Garden"},
{"id":24,"title":"Triple-buffered","description":"Programmable value-added paradigm","image":"http://dummyimage.com/244x100.png/5fa2dd/ffffff","tags":"Baby"},
{"id":25,"title":"application","description":"Intuitive 3rd generation emulation","image":"http://dummyimage.com/125x100.png/dddddd/000000","tags":"Books"},
{"id":26,"title":"Realigned","description":"Ameliorated eco-centric superstructure","image":"http://dummyimage.com/124x100.png/cc0000/ffffff","tags":"Automotive"},
{"id":27,"title":"5th generation","description":"Synergized methodical flexibility","image":"http://dummyimage.com/206x100.png/5fa2dd/ffffff","tags":"Jewelry"},
{"id":28,"title":"concept","description":"Universal bandwidth-monitored utilisation","image":"http://dummyimage.com/169x100.png/5fa2dd/ffffff","tags":"Jewelry"},
{"id":29,"title":"4th generation","description":"Optional next generation flexibility","image":"http://dummyimage.com/212x100.png/5fa2dd/ffffff","tags":"Beauty"},
{"id":30,"title":"Object-based","description":"Robust client-server algorithm","image":"http://dummyimage.com/133x100.png/5fa2dd/ffffff","tags":"Electronics"},
{"id":31,"title":"5th generation","description":"Robust uniform neural-net","image":"http://dummyimage.com/114x100.png/cc0000/ffffff","tags":"Tools"},
{"id":32,"title":"24/7","description":"Vision-oriented cohesive encryption","image":"http://dummyimage.com/130x100.png/dddddd/000000","tags":"Electronics"},
{"id":33,"title":"Advanced","description":"Front-line exuding open system","image":"http://dummyimage.com/228x100.png/dddddd/000000","tags":"Baby"},
{"id":34,"title":"needs-based","description":"Synergized homogeneous internet solution","image":"http://dummyimage.com/126x100.png/ff4444/ffffff","tags":"Sports"},
{"id":35,"title":"Face to face","description":"Balanced zero defect support","image":"http://dummyimage.com/173x100.png/dddddd/000000","tags":"Grocery"},
{"id":36,"title":"algorithm","description":"Reactive 6th generation forecast","image":"http://dummyimage.com/179x100.png/cc0000/ffffff","tags":"Beauty"},
{"id":37,"title":"portal","description":"Ergonomic empowering solution","image":"http://dummyimage.com/113x100.png/ff4444/ffffff","tags":"Outdoors"},
{"id":38,"title":"background","description":"Cloned 5th generation initiative","image":"http://dummyimage.com/239x100.png/cc0000/ffffff","tags":"Electronics"},
{"id":39,"title":"dynamic","description":"Cross-platform directional circuit","image":"http://dummyimage.com/195x100.png/5fa2dd/ffffff","tags":"Movies"},
{"id":40,"title":"framework","description":"Team-oriented next generation success","image":"http://dummyimage.com/132x100.png/dddddd/000000","tags":"Music"},
{"id":41,"title":"Front-line","description":"Implemented local secured line","image":"http://dummyimage.com/248x100.png/cc0000/ffffff","tags":"Beauty"},
{"id":42,"title":"needs-based","description":"Exclusive needs-based project","image":"http://dummyimage.com/235x100.png/5fa2dd/ffffff","tags":"Outdoors"},
{"id":43,"title":"benchmark","description":"Compatible interactive system engine","image":"http://dummyimage.com/165x100.png/5fa2dd/ffffff","tags":"Outdoors"},
{"id":44,"title":"matrix","description":"Front-line bandwidth-monitored task-force","image":"http://dummyimage.com/199x100.png/dddddd/000000","tags":"Kids"},
{"id":45,"title":"User-centric","description":"Re-engineered radical data-warehouse","image":"http://dummyimage.com/145x100.png/cc0000/ffffff","tags":"Computers"},
{"id":46,"title":"algorithm","description":"Public-key bifurcated secured line","image":"http://dummyimage.com/245x100.png/5fa2dd/ffffff","tags":"Sports"},
{"id":47,"title":"Open-source","description":"Up-sized mobile toolset","image":"http://dummyimage.com/218x100.png/5fa2dd/ffffff","tags":"Clothing"},
{"id":48,"title":"Proactive","description":"Face to face maximized definition","image":"http://dummyimage.com/199x100.png/cc0000/ffffff","tags":"Sports"},
{"id":49,"title":"impactful","description":"Extended content-based parallelism","image":"http://dummyimage.com/203x100.png/ff4444/ffffff","tags":"Garden"},
{"id":50,"title":"stable","description":"Down-sized tangible open system","image":"http://dummyimage.com/132x100.png/5fa2dd/ffffff","tags":"Beauty"}]

export const tags=[
    "feature",
    "product",
    "development",
    "devops",
    "tech"
]


